#! /bin/bash

#Verification du nombre de parametre
if [ $# -ne 2 ]
then
  echo "Erreur arguments, deux arguments attendus : <fichier.plic> <classe du fichier>"
  exit 1
fi

#Verification du premier argument
if [ -f $1 ]
then
 if [ -e $1 ]
 then
 vide=0
 else
  echo "Erreur 1er args : fichier inexistant"
  exit 1
  fi
else
echo "Erreur 1er args : ce fichier n'est pas un fichier"
exit 1
fi

#On execute le fichier plic

fichierSortie=$(echo $1 | sed s/'.plic'/''/g)

java -jar Plic1.jar $1 $fichierSortie

#On deplace le fichier asm dans le repertoire tmp
test="$fichierSortie.asm"
if [ -e $test ]
then
mv $test /tmp/$test
else
exit 1
fi
fichierasm="/tmp/$test"

#Execution du fichier asm avec MARS
if [ -e $fichierasm ]
then
varAPasPrendre="MARS 4.5  Copyright 2003-2014 Pete Sanderson and Kenneth Vollmar"
stdbuf -oL java -jar $MARSPATH -1 $fichierasm |
  while IFS= read -r line
  do
	if [ "$line" != "$varAPasPrendre" ] 
	then
		if [ "$line" != "" ]
		then
   		 echo "$line"
		fi

	fi

  done
else
exit 1
fi
exit 0
