
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 10 10:39:01 CEST 2015
//----------------------------------------------------

package modele.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int CSTE = 18;
  public static final int IDF = 17;
  public static final int AND = 13;
  public static final int PLUS = 5;
  public static final int SUP = 9;
  public static final int OR = 14;
  public static final int NOT = 16;
  public static final int MOINS = 6;
  public static final int INF = 10;
  public static final int POINTVIRGULE = 2;
  public static final int PARFER = 4;
  public static final int EOF = 0;
  public static final int MULT = 7;
  public static final int DIV = 8;
  public static final int error = 1;
  public static final int PAROUV = 3;
  public static final int XOR = 15;
  public static final int DIFF = 12;
  public static final int EGA = 11;
}

