
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 09 17:46:57 CEST 2015
//----------------------------------------------------

package modele.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 9;
  public static final int PARFER = 4;
  public static final int MULT = 7;
  public static final int POINTVIRGULE = 2;
  public static final int CSTE = 10;
  public static final int PAROUV = 3;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int DIV = 8;
  public static final int error = 1;
  public static final int MOINS = 6;
}

