
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 12 17:18:24 CEST 2015
//----------------------------------------------------

package modele.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int CSTE = 20;
  public static final int IDF = 19;
  public static final int AND = 15;
  public static final int PLUS = 6;
  public static final int SUP = 10;
  public static final int OR = 16;
  public static final int NOT = 18;
  public static final int VIRGULE = 3;
  public static final int IDFCLASSE = 22;
  public static final int MOINS = 7;
  public static final int INF = 11;
  public static final int POINTVIRGULE = 2;
  public static final int PARFER = 5;
  public static final int TYPE = 27;
  public static final int EGALE = 13;
  public static final int EOF = 0;
  public static final int MULT = 8;
  public static final int DIV = 9;
  public static final int EGALEEGALE = 12;
  public static final int IDFECRIRE = 29;
  public static final int PRIVEE = 26;
  public static final int error = 1;
  public static final int IDFLIRE = 28;
  public static final int PAROUV = 4;
  public static final int BOOL = 21;
  public static final int XOR = 17;
  public static final int DIFF = 14;
  public static final int FIN = 23;
  public static final int PUBLIQUE = 25;
  public static final int CSTECHAINE = 24;
}

